#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    sums = []
    for i in arr:
        if (1<=i<=1000000000):
            sums.append(arr[0]+arr[1]+arr[2]+arr[3]+arr[4]-i)
    print(min(sums),max(sums))

if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)

