#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    n = len(arr)
    pos = 0
    neg = 0
    zero = 0

    if (0<n<=100):
        for i in arr:
            if (-100<= i <=100):
                if (i>0):
                    pos += 1
                if (i<0):
                    neg += 1
                if (i==0):
                    zero += 1

    print(float(pos/n), float(neg/n), float(zero/n), sep='\n' )


if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)

